# Generated by Django 5.1.7 on 2025-03-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["url"], name="feeds_feed_url_200ae1_idx"),
                    models.Index(
                        fields=["last_fetched"], name="feeds_feed_last_fe_bfb4e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("is_read", models.BooleanField(default=False)),
                ("guid", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["feed", "guid"], name="feeds_feedi_feed_id_401d58_idx"
                    ),
                    models.Index(
                        fields=["feed", "published_at"],
                        name="feeds_feedi_feed_id_9bec93_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="feeds_feedi_is_read_17f7b2_idx"
                    ),
                ],
                "unique_together": {("feed", "guid")},
            },
        ),
    ]
